---
output:
  pdf_document: default
  html_document: default
---
```{r}
x<-10
```


```{r}
print(x)
```


```{r}
print(abs(x))
```


```{r}
x<-5.66
print(abs(x))
```


```{r}
y=6
print(sqrt(y))
```


```{r}
m=5.369
print(ceiling(m))
```


```{r}
print(floor(m))
```


```{r}
n<-c(1,2,3.56,5.78)
print(trunc(n))
```
```{r}
print(sin(10))
```


```{r}
print(cos(10))
```
```{r}
print(log(10))
```


```{r}
print(exp(20))
```


```{r}
a<-"1234567891112131415"
substr(a,2,5)
```


```{r}
v<-"BANGLADESH"
print(tolower(v))
```


```{r}
w<-"bangladesh"
toupper(w)
```


```{r}
s2<-c("bangla","abc","english","ma")
sear="^ma"
print(grep(sear,s2))
```


```{r}
s2<-c("ban","abc","english","ma")
sear="^ban"
print(grep(sear,s2))
```
```{r}
g<-c(0:20,30)
print(g)
```


```{r}
print(sum(g))
```


```{r}
h<-max(g)
print(h)

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

