---
output:
  pdf_document: default
  html_document: default
---

```{r}
my_dataframe<-data.frame(employee_id=c(1:5),employee_name=c("shakib","tamim","riyad","masrafi","musfiq"),employee_salary=c(120,330,440,500,210),starting_data=as.Date(c("2022-1-10","2021-02-11","2023-05-15","2021-10-20","2012-11-22")),stringsAsFactors = FALSE)
```




```{r}
my_dataframe
```


```{r}
str(my_dataframe)
```


```{r}
f2<-data.frame(my_dataframe$employee_name,my_dataframe$employee_salary)

```


```{r}
print(f2)
```


```{r}
f3<-my_dataframe[2,]
f3
```


```{r}
f4<-my_dataframe[2:4,]
f4
```
```{r}
a<-my_dataframe[c(2,3),c(1,4)]
a

```

```{r}
a1<-my_dataframe[2,3]
a1
```


```{r}
a2<-my_dataframe[c(2,3)]
a2
```


```{r}
x<-list(6,"rakib",550,"2021-05-14")
```

```{r}
rbind(my_dataframe,x)
```


```{r}
y<-c("dhaka","bangladesh","khulna","rajshai","dinajpur")
```


```{r}
cbind(my_dataframe,Address=y)
```


```{r}
my_dataframe
```


```{r}
my_dataframe<-my_dataframe[-2,]
```


```{r}
my_dataframe
```


```{r}
my_dataframe$starting_data<-NULL
```


```{r}
my_dataframe
```


```{r}
summary(my_dataframe)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


