---
output:
  pdf_document: default
  html_document: default
---
```{r}
my_mat<-matrix(c(2:21),nrow=5,byrow = TRUE)
my_mat
```


```{r}
my_mat<-matrix(c(4,3,5,6,7,8),nrow=2,ncol=3,byrow = FALSE)
my_mat
```


```{r}
x<-matrix(c(5:16),nrow=4,byrow=TRUE)
x
```


```{r}
x<-matrix(c(5:16),nrow=4,byrow=FALSE)
x
```


```{r}
row_name<-c("r1","r2","r3","r4")
col_name<-c("c1","c2","c3")
```


```{r}
z<-matrix(c(7:18),nrow=4,byrow = TRUE,dimnames=list(row_name,col_name))
z
```


```{r}
z[3,1]
```


```{r}
z[4,2]
```


```{r}
z[2,]
```


```{r}
z[3,2]<-100
```


```{r}
z
```


```{r}
z[z==100]<-0

```


```{r}
z[z<15]<-00
```


```{r}
z
```


```{r}
rbind(z,c(2,3,4))
```


```{r}
cbind(z,c(8,9,11,45))
```



```{r}
t(z)
```


```{r}
a1<-matrix(c(5:16),nrow=4,ncol=3,byrow=TRUE)
a1
```


```{r}
b1<-matrix(c(4:15),nrow=4,ncol=3,byrow=TRUE)
b1
```

```{r}
sum<-a1+b1
sum
```


```{r}

```

