

# R Data Types

* numeric

* logical

* complex

* integer

* character

* raw




```{r}

numeric<-c(12,2.50,-255,-24)
print(numeric)

```
```{r}
class(numeric)
```


```{r}
my_integer<-54L
print(my_integer)
```


```{r}
class(my_integer)

```


```{r}
complex<-TRUE,FALSE
print(complex)
```


```{r}
class(complex)
```


```{r}
character<-c("hi","a")

print(character)

```


```{r}
class(character)
```


```{r}
typeof(character)
```


```{r}
int<-15
print(int)
```


```{r}
class(int)
```


```{r}
typeof(int)
```


```{r}
x=as.integer(int)
print(x)
```


```{r}
class(x)
```
```{r}
logi<-TRUE
class(logi)
```


```{r}
chracter<-"jdjdjdvbkjvb"
class(character)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

