---
output:
  pdf_document: default
  html_document: default
---
# arithmetic operation== +,-,*,/,%%,%/%,^

# logical operator== &,|,!,&&,||

# assignment operator == <-,->,->>,<<-,=

# relational operator=== <>,<=,>=,!=


```{r}
a<-5
b<-3.58
c<-a+b
print(c)
```


```{r}
a<-58
b<-65
d<-b-a
print(d)
```


```{r}
x<-6
y<-8
z<-x*y
print(z)
```


```{r}
n<-9
b<-4
c<-n/b
print(c)
```


```{r}
# reminder
h<-30
i<-4
k<-h%%i
print(k)
```


```{r}
#Quotient
a<-10
b<-4
c<-a%/%b
print(c)

```


```{r}
# Power
s<-10
q<-4
t<-q^s
print(t)

```


```{r}
a1=c(2,4,6)
b1=c(8,10,14)
```


```{r}
print(a1+b1)
```


```{r}
print(a1-b1)
```


```{r}
print(a1*b1)
```


```{r}
print(a1/b1)
```


```{r}
print(a1%%b1) 
```


```{r}
print(a1%/%b1)
```


```{r}
print(a1^b1)
```


```{r}
a<-10
b<-20
```


```{r}
print(a>b)
```

```{r}
print(a<b)
```


```{r}
print(a<=b)
```


```{r}
print(a>=b)
```


```{r}
print(a==b)
```


```{r}
print(a!=b)
```


```{r}
a2<-c(2.5,TRUE,5+6i)
b2<-c(6,TRUE,8-5i)
```


```{r}
print(a2&b2)

```


```{r}
print(a2&&b2)
```


```{r}
a3<-c(2,FALSE,5+8i)
b3<-c(2.5,TRUE,45+9i)
```


```{r}
print(a3&b3)
```


```{r}
print(a3&&b3)
```


```{r}

print(a3|b3)
```


```{r}
print(a3||b3)
```


```{r}
print(!a3)
```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

