---
output:
  pdf_document: default
  html_document: default
---


#Data Structures in R

#vectors
#array
#list
#matrix
#data frame

```{r}
a<-c(1,2,3,4.5,6)
a
```


```{r}
b<-10:20
b
```


```{r}
seq<-seq(1,10)
seq
```


```{r}
seq<-seq(1,10,by=2)
seq
```


```{r}
len_out<-seq(1,50,length.out=6)
len_out
```


# Numeric vector

```{r}
n_vec<-c(1,2,3,4,5.66,7,8)
print(n_vec)
class(n_vec)
```


```{r}
int_vec<-c(1,2,3,4,5)
int_vec<-as.integer(int_vec)
class(int_vec)
```


```{r}
int_vec2<-c(3L,6L,7L)
class(int_vec2)
```


```{r}
char<-c(1,2,3,4,5)
char<-as.character(char)
class(char)
```


```{r}
char1<-c("shakib","tamim","riyad","musfiq")
class(char1)
print(char1)
```


```{r}
char_vec<-c("shakib"=12,"tamim"=30,"riyad"=60)
char_vec["tamim"]
```


```{r}
a<-c(1,2,5,4,6,7,9,10)
a[c(TRUE,FALSE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE)]
```
```{r}
b1<-c(1,2,3)
b2<-c("rakib","tamim","fariha")
b3<-c(b1,b2)
print(b3)
```


```{r}
b4<-c(1,2,3,8,9,10)
b5<-c(1,2,3,5,4,8)
b6<-b4+b5
print(b6)

```


```{r}
v<-c("rakib","tamim","fariha","shabnur")
v[2]
v[-2]
v[-1]
v[c(2,3,1,2)]
v[1: 2]
```


```{r}
z<-c("bangla","english","math","biology","physics")
z

```


```{r}
names(z)=c("a1","b1","c1","d1","e")

z["b1"]
z["e"]
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

